# Глобальные настройки Prometheus
global:
  scrape_interval: 15s # Как часто забирать метрики. 15 секунд - стандарт.
  evaluation_interval: 15s # Как часто пересчитывать правила алертинга.

# Список источников, откуда нужно забирать метрики.
scrape_configs:
  # Первая "задача" (job) - собирать метрики с самого Prometheus.
  # Это полезно для мониторинга самого сборщика метрик.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Вторая и НАША ГЛАВНАЯ задача - собирать метрики с нашего Go-приложения.
  - job_name: "trello-app"
    # `dns_sd_configs` - это способ для Prometheus автоматически находить цели
    # через DNS. В Docker Compose это самый удобный способ.
    dns_sd_configs:
      - names:
          # Имя сервиса нашего приложения, как оно будет указано в docker-compose.yml.
          - "app"
        type: "A"
        port: 8080 # Порт, на котором наше приложение отдает метрики.