basePath: /api
definitions:
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.Board:
    properties:
      created_at:
        type: string
      id:
        type: integer
      lists:
        items:
          $ref: '#/definitions/models.List'
        type: array
      members:
        items:
          $ref: '#/definitions/models.User'
        type: array
      name:
        type: string
      owner_id:
        type: integer
      updated_at:
        type: string
    type: object
  models.Card:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      list_id:
        type: integer
      position:
        type: number
      title:
        type: string
      updated_at:
        type: string
    type: object
  models.List:
    properties:
      board_id:
        type: integer
      cards:
        items:
          $ref: '#/definitions/models.Card'
        type: array
      created_at:
        type: string
      id:
        type: integer
      position:
        type: number
      title:
        type: string
      updated_at:
        type: string
    type: object
  models.User:
    properties:
      age:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      updated_at:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Это API для клона Trello, созданного на Go.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Trello Clone API
  version: "1.0"
paths:
  /boards:
    get:
      description: Возвращает список всех досок, где пользователь является владельцем
        или участником.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Board'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Получить все доски пользователя
      tags:
      - Boards
  /boards/{boardId}:
    get:
      description: Возвращает полную информацию о доске, включая списки и карточки.
      parameters:
      - description: ID Доски
        in: path
        name: boardId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Board'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Получить доску по ID
      tags:
      - Boards
securityDefinitions:
  ApiKeyAuth:
    description: Введите "Bearer" пробел и затем ваш JWT токен.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
